const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
const puppeteer = require("puppeteer");

const aiTimeoutMs = Number(process.env.GEMINI_TIMEOUT_MS || 12000);
const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY,
    httpOptions: {
        timeout: aiTimeoutMs,
        retryOptions: {
            attempts: 1,
            httpStatusCodes: [429, 500, 502, 503, 504]
        }
    }
});
const geminiModel = process.env.GEMINI_MODEL || "gemini-3.5-flash-lite";

const interviewReportSchema = z.object({
    candidate_name: z.string(),
    target_role: z.string(),
    match_score: z.number().min(0).max(100),
    math_score: z.number().min(0).max(100),
    summary: z.string(),
    technical_questions: z.array(z.string()).min(5),
    behavioral_questions: z.array(z.string()).min(4),
    skill_gaps: z.array(z.string()).min(3),
    preparation_plan: z.array(z.string()).min(4)
});

async function generateInterviewReport({
    resume,
    selfDescription,
    jobDescription
}) {
    if (!process.env.GOOGLE_GENAI_API_KEY) {
        const error = new Error("GOOGLE_GENAI_API_KEY is not configured");
        error.status = 503;
        throw error;
    }

    const prompt = `
Generate an interview report for a candidate based on the following information.

Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}

Create a useful interview preparation report with:
- candidate_name: the candidate's name
- target_role: the job title
- match_score: an integer from 0 to 100
- math_score: an integer from 0 to 100 estimating aptitude for the role's quantitative and logical problem-solving requirements
- summary: a concise assessment of the candidate's fit
- technical_questions: at least 5 role-specific technical questions
- behavioral_questions: at least 4 behavioral questions
- skill_gaps: at least 3 concrete skill gaps
- preparation_plan: at least 4 specific preparation actions

Return exactly one JSON object with exactly these property names. Do not return an array,
markdown, code fences, or any text outside the JSON object.
The content should be ATS-friendly, professional, and human-like, avoiding any AI-generated tone.
The resume should not be length , it should ideally be 1-2 pages long, and the report should be concise, clear, and actionable.
`;

    const response = await ai.models.generateContent({
        model: geminiModel,
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(interviewReportSchema)
        }
    });

    if (!response || typeof response.text !== "string" || !response.text.trim()) {
        const error = new Error("Gemini returned an empty response");
        error.status = 502;
        throw error;
    }

    try {
        return interviewReportSchema.parse(JSON.parse(response.text));
    } catch (error) {
        const responseError = new Error(`Gemini returned an invalid interview report: ${error.message}`);
        responseError.status = 502;
        throw responseError;
    }
}

async function generatePdfFormHtml(htmlContent){
    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    try {
        const page = await browser.newPage();
        await page.setContent(htmlContent, { waitUntil: 'domcontentloaded' });
        return await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' }
        });
    } finally {
        await browser.close();
    }
}

async function generateResumePdf({resume, selfDescription, jobDescription}) {
    if (!process.env.GOOGLE_GENAI_API_KEY) {
        const error = new Error("GOOGLE_GENAI_API_KEY is not configured");
        error.status = 503;
        throw error;
    }

    const resumePdfSchema = z.object({
        html: z.string().describe("HTML content of the resume PDF")
    })
    const prompt = `Generate a resume based on the following information.
    
    Resume:
    ${resume}

    Self Description:
    ${selfDescription}

    Job Description:
    ${jobDescription}
    the response should be a JSON object with a single field "html" containing the HTML content of the resume PDF. The HTML should be well-structured and formatted for a professional resume.
    The response should be tailored for the given job description and self-description, highlighting relevant skills and experiences. The HTML should be suitable for conversion to a PDF format. Do not include any additional text or explanations outside of the JSON object.
    The content of resume should not sound like it's generated by AI, it should be human-like and professional. The HTML should be responsive and visually appealing, with appropriate use of headings, bullet points, and sections to organize the information effectively. Ensure that the resume is concise, clear, and highlights the candidate's strengths and qualifications for the specified job role.`;

    const response = await ai.models.generateContent({
        model: geminiModel,
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema)
        }
    })

    if (!response || typeof response.text !== "string" || !response.text.trim()) {
        const error = new Error("Gemini returned an empty resume response");
        error.status = 502;
        throw error;
    }

    let jsonContent;
    try {
        jsonContent = resumePdfSchema.parse(JSON.parse(response.text));
    } catch (error) {
        const responseError = new Error(`Gemini returned invalid resume content: ${error.message}`);
        responseError.status = 502;
        throw responseError;
    }

    const pdfBuffer = await generatePdfFormHtml(jsonContent.html);
    return pdfBuffer;
}

module.exports = {
    generateInterviewReport,generateResumePdf
};